using System;
using System.Collections.Generic;
using System.Globalization;
using System.Numerics;
using Dalamud.Bindings.ImGui;

namespace WispUI.Style;

/// <summary>
/// One icon as the drawing needs it: a few outlines on a 24 by 24 grid, already flattened to
/// points.
/// <para>
/// Built once from the shape data and kept. The draw path walks points and nothing else — no
/// parsing, no curve maths, no allocation.
/// </para>
/// </summary>
internal sealed class LineIcon
{
    public LineIcon(Vector2[][] outlines, bool[] closed, Vector3[] circles)
    {
        this.Outlines = outlines;
        this.Closed = closed;
        this.Circles = circles;
    }

    /// <summary>Each stroke of the icon, as points on the 24 grid.</summary>
    public Vector2[][] Outlines { get; }

    /// <summary>Whether each outline joins back to its start.</summary>
    public bool[] Closed { get; }

    /// <summary>Circles the icon draws, as centre and radius on the same grid.</summary>
    public Vector3[] Circles { get; }
}

/// <summary>
/// WispUI's line icons, drawn from vector outlines rather than from a font or a picture.
/// <para>
/// 🔴 The shapes come from <b>Lucide</b> (lucide.dev), ISC licence, copyright Lucide Icons and
/// Contributors — the same set LumenUI uses, which is why they are here: one look across both
/// projects, and a set we control rather than whatever an icon font happens to ship. The
/// licence text is kept beside them in <c>Icons/LUCIDE-LICENSE.txt</c> and must stay with any
/// copy of this plugin. Each entry below names the file it was taken from, unchanged.
/// </para>
/// <para>
/// 🔴 Why vectors and not a font: Lucide publishes no font file — theirs is generated by a
/// build we do not run — and the alternative that was tried first, the icon face Dalamud
/// bundles, drew empty boxes (Florian, 2026-09-19). Drawing the outlines has the better
/// properties anyway: sharp at any size, our own colour, and a new icon is one string.
/// </para>
/// <para>
/// Lucide draws on a 24 by 24 grid with a 2 wide stroke, round caps and round joins. Those
/// are the numbers below, and keeping them is what makes a WispUI icon look like a Lucide
/// icon rather than like a traced one.
/// </para>
/// </summary>
internal static class LineIcons
{
    /// <summary>The grid every outline is stated on.</summary>
    public const float Grid = 24f;

    /// <summary>Lucide's own stroke width, on that grid.</summary>
    public const float Stroke = 2f;

    // --- the set, each taken from the file named beside it --------------------

    /// <summary>eye.svg</summary>
    public static LineIcon Eye => Get(
        "eye",
        new[] { "M2.062 12.348a1 1 0 0 1 0-.696 10.75 10.75 0 0 1 19.876 0 1 1 0 0 1 0 .696 10.75 10.75 0 0 1-19.876 0" },
        new[] { new Vector3(12f, 12f, 3f) });

    /// <summary>eye-off.svg</summary>
    public static LineIcon EyeOff => Get(
        "eye-off",
        new[]
        {
            "M10.733 5.076a10.744 10.744 0 0 1 11.205 6.575 1 1 0 0 1 0 .696 10.747 10.747 0 0 1-1.444 2.49",
            "M14.084 14.158a3 3 0 0 1-4.242-4.242",
            "M17.479 17.499a10.75 10.75 0 0 1-15.417-5.151 1 1 0 0 1 0-.696 10.75 10.75 0 0 1 4.446-5.143",
            "m2 2 20 20",
        },
        Array.Empty<Vector3>());

    /// <summary>rotate-ccw.svg</summary>
    public static LineIcon RotateCcw => Get(
        "rotate-ccw",
        new[]
        {
            "M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8",
            "M3 3v5h5",
        },
        Array.Empty<Vector3>());

    /// <summary>
    /// Draws an icon into a square box, scaled from the 24 grid.
    /// <para>
    /// The stroke scales with it, so a small icon keeps Lucide's proportions instead of
    /// turning into a thick blob — but never below one pixel, which is the same rule
    /// <see cref="Tokens.Line"/> follows for every other edge in the suite.
    /// </para>
    /// </summary>
    public static void Draw(ImDrawListPtr dl, LineIcon icon, Vector2 min, float size, uint colour)
    {
        float scale = size / Grid;
        float thickness = MathF.Max(1f, MathF.Round(Stroke * scale));

        for (int i = 0; i < icon.Outlines.Length; i++)
        {
            Vector2[] points = icon.Outlines[i];

            if (points.Length < 2)
            {
                continue;
            }

            dl.PathClear();

            for (int p = 0; p < points.Length; p++)
            {
                dl.PathLineTo(new Vector2(min.X + (points[p].X * scale), min.Y + (points[p].Y * scale)));
            }

            dl.PathStroke(colour, icon.Closed[i] ? ImDrawFlags.Closed : ImDrawFlags.None, thickness);
        }

        for (int i = 0; i < icon.Circles.Length; i++)
        {
            Vector3 circle = icon.Circles[i];
            dl.AddCircle(
                new Vector2(min.X + (circle.X * scale), min.Y + (circle.Y * scale)),
                circle.Z * scale,
                colour,
                0,
                thickness);
        }
    }

    /// <summary>
    /// The icon for this name, built on the first ask and kept afterwards.
    /// <para>
    /// Parsing happens here and only here, which is what keeps it out of the draw path — an
    /// icon is asked for by name every frame and answered from the dictionary.
    /// </para>
    /// </summary>
    private static LineIcon Get(string name, string[] paths, Vector3[] circles)
    {
        if (Cache.TryGetValue(name, out LineIcon? known))
        {
            return known;
        }

        var outlines = new List<Vector2[]>();
        var closed = new List<bool>();

        for (int i = 0; i < paths.Length; i++)
        {
            Flatten(paths[i], outlines, closed);
        }

        var built = new LineIcon(outlines.ToArray(), closed.ToArray(), circles);
        Cache[name] = built;
        return built;
    }

    private static readonly Dictionary<string, LineIcon> Cache = new();

    /// <summary>
    /// How many straight pieces a curve is cut into. Twelve is invisible at the sizes an icon
    /// is drawn at and would still be at four times that.
    /// </summary>
    private const int CurveSteps = 12;

    /// <summary>
    /// Turns one SVG path into points.
    /// <para>
    /// Everything is sampled rather than converted: a curve and an arc both come out as a run
    /// of points, so the drawing has one case to handle instead of four. The subset supported
    /// is the one Lucide writes — move, line, horizontal, vertical, cubic, smooth cubic,
    /// quadratic, smooth quadratic, arc and close, in both cases.
    /// </para>
    /// </summary>
    private static void Flatten(string d, List<Vector2[]> outlines, List<bool> closed)
    {
        var points = new List<Vector2>();
        int at = 0;
        char command = ' ';
        Vector2 cursor = default;
        Vector2 start = default;

        // The control point a smooth curve mirrors. Kept between commands, which is the whole
        // point of the smooth forms.
        Vector2 lastCubic = default;
        Vector2 lastQuad = default;
        char previous = ' ';

        while (true)
        {
            SkipSeparators(d, ref at);

            if (at >= d.Length)
            {
                break;
            }

            if (char.IsLetter(d[at]))
            {
                command = d[at];
                at++;
            }
            else if (command == 'M')
            {
                // A repeated coordinate pair after a move is a line, per the specification.
                command = 'L';
            }
            else if (command == 'm')
            {
                command = 'l';
            }

            bool relative = char.IsLower(command);
            Vector2 origin = relative ? cursor : default;

            switch (char.ToUpperInvariant(command))
            {
                case 'M':
                    Close(points, outlines, closed, false);
                    cursor = origin + ReadPoint(d, ref at);
                    start = cursor;
                    points.Add(cursor);
                    break;

                case 'L':
                    cursor = origin + ReadPoint(d, ref at);
                    points.Add(cursor);
                    break;

                case 'H':
                    cursor = new Vector2((relative ? cursor.X : 0f) + ReadNumber(d, ref at), cursor.Y);
                    points.Add(cursor);
                    break;

                case 'V':
                    cursor = new Vector2(cursor.X, (relative ? cursor.Y : 0f) + ReadNumber(d, ref at));
                    points.Add(cursor);
                    break;

                case 'C':
                {
                    Vector2 c1 = origin + ReadPoint(d, ref at);
                    Vector2 c2 = origin + ReadPoint(d, ref at);
                    Vector2 end = origin + ReadPoint(d, ref at);
                    SampleCubic(points, cursor, c1, c2, end);
                    lastCubic = c2;
                    cursor = end;
                    break;
                }

                case 'S':
                {
                    Vector2 c1 = previous is 'C' or 'c' or 'S' or 's' ? (cursor * 2f) - lastCubic : cursor;
                    Vector2 c2 = origin + ReadPoint(d, ref at);
                    Vector2 end = origin + ReadPoint(d, ref at);
                    SampleCubic(points, cursor, c1, c2, end);
                    lastCubic = c2;
                    cursor = end;
                    break;
                }

                case 'Q':
                {
                    Vector2 c = origin + ReadPoint(d, ref at);
                    Vector2 end = origin + ReadPoint(d, ref at);
                    SampleQuadratic(points, cursor, c, end);
                    lastQuad = c;
                    cursor = end;
                    break;
                }

                case 'T':
                {
                    Vector2 c = previous is 'Q' or 'q' or 'T' or 't' ? (cursor * 2f) - lastQuad : cursor;
                    Vector2 end = origin + ReadPoint(d, ref at);
                    SampleQuadratic(points, cursor, c, end);
                    lastQuad = c;
                    cursor = end;
                    break;
                }

                case 'A':
                {
                    float rx = ReadNumber(d, ref at);
                    float ry = ReadNumber(d, ref at);
                    float rotation = ReadNumber(d, ref at);
                    bool large = ReadNumber(d, ref at) != 0f;
                    bool sweep = ReadNumber(d, ref at) != 0f;
                    Vector2 end = origin + ReadPoint(d, ref at);
                    SampleArc(points, cursor, end, rx, ry, rotation, large, sweep);
                    cursor = end;
                    break;
                }

                case 'Z':
                    Close(points, outlines, closed, true);
                    cursor = start;
                    break;

                default:
                    // An unknown letter would otherwise spin here forever reading nothing.
                    return;
            }

            previous = command;
        }

        Close(points, outlines, closed, false);
    }

    private static void Close(List<Vector2> points, List<Vector2[]> outlines, List<bool> closed, bool joined)
    {
        if (points.Count >= 2)
        {
            // A path that ends where it began is a loop whether or not it says Z — the eye is
            // exactly that, four arcs back to the start. Left open, the two ends would meet as
            // two square ends rather than as a join, which shows as a notch at the point of
            // the almond. The last point goes with the flag, or it would be drawn twice.
            if (!joined && Vector2.Distance(points[0], points[^1]) < 0.01f)
            {
                points.RemoveAt(points.Count - 1);
                joined = true;
            }

            outlines.Add(points.ToArray());
            closed.Add(joined);
        }

        points.Clear();
    }

    private static void SampleCubic(List<Vector2> points, Vector2 p0, Vector2 c1, Vector2 c2, Vector2 p1)
    {
        for (int i = 1; i <= CurveSteps; i++)
        {
            float t = (float)i / CurveSteps;
            float u = 1f - t;
            points.Add((u * u * u * p0) + (3f * u * u * t * c1) + (3f * u * t * t * c2) + (t * t * t * p1));
        }
    }

    private static void SampleQuadratic(List<Vector2> points, Vector2 p0, Vector2 c, Vector2 p1)
    {
        for (int i = 1; i <= CurveSteps; i++)
        {
            float t = (float)i / CurveSteps;
            float u = 1f - t;
            points.Add((u * u * p0) + (2f * u * t * c) + (t * t * p1));
        }
    }

    /// <summary>
    /// Samples an SVG elliptical arc.
    /// <para>
    /// The specification states an arc by where it ends, not by where its centre is, so the
    /// centre has to be worked back out — that is what all of this is. Sampled straight from
    /// the angle rather than turned into curves first: we are flattening either way, and
    /// going through beziers would only add a second approximation.
    /// </para>
    /// </summary>
    private static void SampleArc(
        List<Vector2> points,
        Vector2 from,
        Vector2 to,
        float rx,
        float ry,
        float rotationDegrees,
        bool large,
        bool sweep)
    {
        if (rx == 0f || ry == 0f || from == to)
        {
            points.Add(to);
            return;
        }

        rx = MathF.Abs(rx);
        ry = MathF.Abs(ry);

        float phi = rotationDegrees * MathF.PI / 180f;
        float cosPhi = MathF.Cos(phi);
        float sinPhi = MathF.Sin(phi);

        Vector2 half = (from - to) * 0.5f;
        Vector2 turned = new(
            (cosPhi * half.X) + (sinPhi * half.Y),
            (-sinPhi * half.X) + (cosPhi * half.Y));

        // Radii too small to reach are grown until they just do, which is what the
        // specification says to do rather than treat the path as broken.
        float check = ((turned.X * turned.X) / (rx * rx)) + ((turned.Y * turned.Y) / (ry * ry));

        if (check > 1f)
        {
            float grow = MathF.Sqrt(check);
            rx *= grow;
            ry *= grow;
        }

        float numerator = (rx * rx * ry * ry)
            - (rx * rx * turned.Y * turned.Y)
            - (ry * ry * turned.X * turned.X);
        float denominator = (rx * rx * turned.Y * turned.Y) + (ry * ry * turned.X * turned.X);
        float factor = denominator <= 0f ? 0f : MathF.Sqrt(MathF.Max(0f, numerator / denominator));

        if (large == sweep)
        {
            factor = -factor;
        }

        Vector2 centreTurned = new(
            factor * rx * turned.Y / ry,
            -factor * ry * turned.X / rx);

        Vector2 mid = (from + to) * 0.5f;
        Vector2 centre = new(
            (cosPhi * centreTurned.X) - (sinPhi * centreTurned.Y) + mid.X,
            (sinPhi * centreTurned.X) + (cosPhi * centreTurned.Y) + mid.Y);

        float startAngle = Angle(
            1f,
            0f,
            (turned.X - centreTurned.X) / rx,
            (turned.Y - centreTurned.Y) / ry);

        float delta = Angle(
            (turned.X - centreTurned.X) / rx,
            (turned.Y - centreTurned.Y) / ry,
            (-turned.X - centreTurned.X) / rx,
            (-turned.Y - centreTurned.Y) / ry);

        float twoPi = MathF.PI * 2f;
        delta %= twoPi;

        if (!sweep && delta > 0f)
        {
            delta -= twoPi;
        }
        else if (sweep && delta < 0f)
        {
            delta += twoPi;
        }

        // More pieces for more turn, so a quarter circle and a near-full one are equally
        // smooth. A Lucide arc is rarely more than a half.
        int steps = Math.Max(2, (int)MathF.Ceiling(MathF.Abs(delta) / (MathF.PI / CurveSteps)));

        for (int i = 1; i <= steps; i++)
        {
            float angle = startAngle + (delta * i / steps);
            float x = rx * MathF.Cos(angle);
            float y = ry * MathF.Sin(angle);

            points.Add(new Vector2(
                (cosPhi * x) - (sinPhi * y) + centre.X,
                (sinPhi * x) + (cosPhi * y) + centre.Y));
        }
    }

    /// <summary>The signed angle from one vector to another.</summary>
    private static float Angle(float ux, float uy, float vx, float vy)
    {
        float dot = (ux * vx) + (uy * vy);
        float lengths = MathF.Sqrt(((ux * ux) + (uy * uy)) * ((vx * vx) + (vy * vy)));
        float angle = lengths <= 0f ? 0f : MathF.Acos(Math.Clamp(dot / lengths, -1f, 1f));

        return ((ux * vy) - (uy * vx)) < 0f ? -angle : angle;
    }

    private static void SkipSeparators(string d, ref int at)
    {
        while (at < d.Length && (d[at] == ' ' || d[at] == ',' || d[at] == '\r' || d[at] == '\n' || d[at] == '\t'))
        {
            at++;
        }
    }

    private static Vector2 ReadPoint(string d, ref int at) => new(ReadNumber(d, ref at), ReadNumber(d, ref at));

    /// <summary>
    /// Reads one number, in the shapes SVG allows: a sign that is also a separator, a leading
    /// dot, and a second dot that begins the next number without any space between them.
    /// </summary>
    private static float ReadNumber(string d, ref int at)
    {
        SkipSeparators(d, ref at);

        int from = at;
        bool seenDot = false;

        if (at < d.Length && (d[at] == '-' || d[at] == '+'))
        {
            at++;
        }

        while (at < d.Length)
        {
            char c = d[at];

            if (c >= '0' && c <= '9')
            {
                at++;
                continue;
            }

            if (c == '.' && !seenDot)
            {
                seenDot = true;
                at++;
                continue;
            }

            break;
        }

        return at > from && float.TryParse(d.AsSpan(from, at - from), NumberStyles.Float, CultureInfo.InvariantCulture, out float value)
            ? value
            : 0f;
    }
}
